#!/usr/bin/env bash
# Asserts the kit registers the SAME hook set in both install modes, and that a
# project initialized by scripts/sdlc-init.cjs ends up with registrations that
# match the hook files actually copied into it.
#
# THE DEFECT THIS LOCKS DOWN (found 2026-09-10)
# The kit ships two registration surfaces for two install modes:
#   plugin mode   -> hooks/hooks.json                  (${CLAUDE_PLUGIN_ROOT})
#   vendored mode -> settings/original-settings.json   ($CLAUDE_PROJECT_DIR),
#                    merged into a project by scripts/sdlc-init.cjs
# They were maintained by hand and drifted: the vendored template was missing
# seven hooks and the whole Stop event, while carrying a standalone
# dispatch-journal-gc entry the plugin manifest drops (it runs in-process via
# session-init-summary, so a standalone entry double-runs it).
#
# The consequence was not cosmetic: sdlc-init COPIES the whole hooks/ directory
# into a project but merges only the template's registrations. So a vendored
# project got new hook FILES on disk with old REGISTRATIONS in settings.json —
# hooks physically present and never invoked. That is the "documented as
# hook-enforced, enforced by nothing" symptom, and this template produced it.
#
# settings/original-settings.json is now GENERATED by
# scripts/sync-settings-template.cjs. These tests fail if it is hand-edited out
# of sync again.
#
# Usage:  bash hooks/tests/test-vendored-parity.sh

set -u
HOOKS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$HOOKS_DIR/.." && pwd)"
PASS=0; FAIL=0
S="$(mktemp -d)"
trap 'rm -rf "$S"' EXIT

ok()   { printf "  PASS  %s\n" "$1"; PASS=$((PASS+1)); }
bad()  { printf "  FAIL  %s\n" "$1"; shift; [ $# -gt 0 ] && printf "        %s\n" "$*"; FAIL=$((FAIL+1)); }

echo "generated template is in sync with the plugin manifest"
if node "$ROOT/scripts/sync-settings-template.cjs" --check >"$S/out" 2>"$S/err"; then
  ok "sync-settings-template --check reports no drift"
else
  bad "settings/original-settings.json has drifted from hooks/hooks.json" "$(sed -n '1,12p' "$S/err")"
fi

echo "the generator is idempotent (running it changes nothing)"
cp "$ROOT/settings/original-settings.json" "$S/before.json"
node "$ROOT/scripts/sync-settings-template.cjs" >/dev/null 2>&1
if cmp -s "$S/before.json" "$ROOT/settings/original-settings.json"; then
  ok "regeneration is a no-op"
else
  bad "regeneration mutated the committed template"
  cp "$S/before.json" "$ROOT/settings/original-settings.json"
fi

echo "every registration in the template points at a hook file that exists"
node -e '
const fs=require("fs"),path=require("path");
const root=process.argv[1];
const d=JSON.parse(fs.readFileSync(path.join(root,"settings/original-settings.json"),"utf8"));
const missing=[];
for(const [ev,gs] of Object.entries(d.hooks||{}))
  for(const g of gs) for(const h of g.hooks||[]){
    const m=/\/hooks\/([A-Za-z0-9._-]+\.cjs)/.exec(h.command||"");
    if(!m){missing.push([ev,"unparseable: "+h.command]);continue;}
    if(!fs.existsSync(path.join(root,"hooks",m[1]))) missing.push([ev,m[1]]);
  }
if(missing.length){console.error(JSON.stringify(missing));process.exit(1);}
' "$ROOT" 2>"$S/err" && ok "no dangling registrations" || bad "template registers missing files" "$(cat "$S/err")"

echo "no hook file is left unregistered in either mode"
node -e '
const fs=require("fs"),path=require("path");
const root=process.argv[1];
// dispatch-journal-gc is required in-process by session-init-summary, so it is
// intentionally not registered standalone in either surface.
const IN_PROCESS=new Set(["dispatch-journal-gc.cjs"]);
const names=src=>{const out=new Set();
  for(const [ev,gs] of Object.entries(src.hooks||{}))
    for(const g of gs) for(const h of g.hooks||[]){
      const s=(h.command||"")+" "+((h.args||[]).join(" "));
      const m=/([A-Za-z0-9._-]+\.cjs)/.exec(s); if(m) out.add(m[1]);}
  return out;};
const man=names(JSON.parse(fs.readFileSync(path.join(root,"hooks/hooks.json"),"utf8")));
const tpl=names(JSON.parse(fs.readFileSync(path.join(root,"settings/original-settings.json"),"utf8")));
const disk=fs.readdirSync(path.join(root,"hooks")).filter(f=>f.endsWith(".cjs"));
const problems=[];
for(const f of disk){ if(IN_PROCESS.has(f)) continue;
  if(!man.has(f)) problems.push(`${f} not in hooks/hooks.json`);
  if(!tpl.has(f)) problems.push(`${f} not in settings/original-settings.json`);}
if(problems.length){console.error(problems.join("; "));process.exit(1);}
' "$ROOT" 2>"$S/err" && ok "every hook file is registered in both surfaces" || bad "unregistered hook files" "$(cat "$S/err")"

echo "sdlc-init produces a coherent vendored project"
PROJ="$S/proj"; mkdir -p "$PROJ"
( cd "$PROJ" && git init -q -b main && git config user.email t@e.com && git config user.name T )
if node "$ROOT/scripts/sdlc-init.cjs" --project "$PROJ" --target claude >"$S/init.out" 2>"$S/init.err"; then
  ok "sdlc-init exits 0"
else
  bad "sdlc-init failed" "$(tail -5 "$S/init.err")"
fi

if [ -f "$PROJ/.claude/settings.json" ]; then ok "wrote .claude/settings.json"; else bad "no .claude/settings.json"; fi
if [ -f "$PROJ/.claude/kit-lineage.json" ]; then
  got=$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).lineage)' "$PROJ/.claude/kit-lineage.json")
  [ "$got" = "ingestion" ] && ok "declared the ingestion lineage in the project" || bad "wrong lineage: $got"
else
  bad "no .claude/kit-lineage.json written — foreign-lineage guards cannot stand down"
fi

echo "vendored project: registrations match the files copied in"
node -e '
const fs=require("fs"),path=require("path");
const proj=process.argv[1];
const IN_PROCESS=new Set(["dispatch-journal-gc.cjs"]);
const sp=path.join(proj,".claude/settings.json");
if(!fs.existsSync(sp)){console.error("no settings.json");process.exit(1);}
const d=JSON.parse(fs.readFileSync(sp,"utf8"));
const reg=new Set();
for(const [ev,gs] of Object.entries(d.hooks||{}))
  for(const g of gs) for(const h of g.hooks||[]){
    const m=/([A-Za-z0-9._-]+\.cjs)/.exec(h.command||""); if(m) reg.add(m[1]);}
const hd=path.join(proj,".claude/hooks");
const disk=fs.existsSync(hd)?fs.readdirSync(hd).filter(f=>f.endsWith(".cjs")):[];
const unreg=disk.filter(f=>!reg.has(f)&&!IN_PROCESS.has(f));
const dangling=[...reg].filter(f=>!disk.includes(f));
if(unreg.length||dangling.length){
  console.error("copied-but-unregistered: "+JSON.stringify(unreg)+"  registered-but-absent: "+JSON.stringify(dangling));
  process.exit(1);}
console.log("registrations:"+reg.size+" files:"+disk.length);
' "$PROJ" >"$S/p.out" 2>"$S/p.err" && ok "no copied-but-unregistered and no dangling ($(cat "$S/p.out"))" \
  || bad "vendored project is incoherent" "$(cat "$S/p.err")"

echo "release integrity: identities agree and the shipped surface matches the version"
# Byte-identical, not merely equal-after-normalizing: "0.7" and "0.7.0" mean the
# same release but compare unequal to exact-match tooling, and both shapes have
# already shipped here.
node -e '
const fs=require("fs"),path=require("path");const r=process.argv[1];
const a=JSON.parse(fs.readFileSync(path.join(r,".claude-plugin/plugin.json"),"utf8")).version;
const b=JSON.parse(fs.readFileSync(path.join(r,".claude-plugin/marketplace.json"),"utf8")).plugins[0].version;
const c=JSON.parse(fs.readFileSync(path.join(r,".codex-plugin/plugin.json"),"utf8")).version;
if(!(a===b&&b===c)){console.error(`plugin=${JSON.stringify(a)} marketplace=${JSON.stringify(b)} codex=${JSON.stringify(c)}`);process.exit(1);}
if(!/^\d+\.\d+\.\d+$/.test(a)){console.error("not MAJOR.MINOR.PATCH: "+JSON.stringify(a));process.exit(1);}
console.log(a);
' "$ROOT" >"$S/v.out" 2>"$S/v.err" && ok "all manifests byte-identical at $(cat "$S/v.out")" || bad "version identities disagree" "$(cat "$S/v.err")"

# The rule "a behaviour change requires a version bump" was written on
# 2026-09-10 and broken twice in three days, including by the change that
# introduced it. Prose could not hold it; this can.
if node "$ROOT/scripts/check-release-version.cjs" >"$S/r.out" 2>"$S/r.err"; then
  ok "shipped surface matches the recorded release"
else
  bad "shipped surface changed without a version bump" "$(sed -n '1,6p' "$S/r.err")"
fi

printf "\n  %s passed, %s failed\n" "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
